//go:build ignore

// gen_engines.go scans internal/engine/ for game engine packages and writes
// engines_gen.go with the blank side-effect imports needed to trigger init().
//
// Usage (from repo root or backend/):
//
//	go generate ./cmd/api/...
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	engineDir  = "../../internal/engine"
	outputFile = "engines_gen.go"
	modulePath = "github.com/x-game/backend/internal/engine"
)

func main() {
	entries, err := os.ReadDir(engineDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading %s: %v\n", engineDir, err)
		os.Exit(1)
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		// Only include directories that contain at least one non-test .go file.
		subs, _ := os.ReadDir(filepath.Join(engineDir, e.Name()))
		for _, f := range subs {
			if strings.HasSuffix(f.Name(), ".go") && !strings.HasSuffix(f.Name(), "_test.go") {
				names = append(names, e.Name())
				break
			}
		}
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("// Code generated by \"go generate ./cmd/api/...\"; DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\nimport (\n")
	for _, name := range names {
		fmt.Fprintf(&sb, "\t_ \"%s/%s\"\n", modulePath, name)
	}
	sb.WriteString(")\n")

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}
	fmt.Printf("generated %s (%d engines: %s)\n", outputFile, len(names), strings.Join(names, ", "))
}
